### ISSUE TITLE
viability plotting is broken

### ISSUE THREAD

**Issue by sheim** [sheim/slippy#17]
When changing the data-type to pickle, I tested the demos again and found that the `viability_plot` doesn't work. I tried rolling back a bit but it seems to have been broken for a while, I hadn't noticed before.

I poked around and I think this is due to the way `initial_state` is initialized. It makes some assumptions on the grids being one-dimensional, which don't fit in the generalized code (where `s_grid` is a tuple of grids, and each grid can be a different length).

I made a couple changes in the branch `viab_plot` (3f0a81c4ed27cdddafaf8db4f26aa31f92cd282e), but I'm there are still indexing problems.

**Comment by charlotte-lemouel** [comment]
I've added a function to visualise_viability which does not take a dict and I've modified the demo, cf pull request.

**Comment by sheim** [comment]
Nice, thanks.
