### ISSUE TITLE
Choice of measure

### ISSUE THREAD

**Issue by sheim** [sheim/slippy#24]
So, I've thought a bit about the measure, and why taking the width and not integrating is good.
If we integrate, we are looking into the future _recursively_ since we are taking into consideration the measure at the next step, which depends on the actions taken, which depend on where they land, which depend on the next step....  
  
This is a problem for three reasons. First, this means we have to take into consideration the policy applied to the system. Kind of the same problem as with off-policy learning. If there is noise, we need to also consider the distribution of the noise (although this is more of a technical difficulty).  

Second, the above also means two states with the same measure with our current measure, may or may not have the same measure in truth: this will depend on the policy applied. Since our active-sampling (policy) depends on this measure, I'm less confident this actually converges.

I'll think of a third reasons later.

**Comment by alexBeuth** [comment]
I don't follow this reasoning. Integrating over all actions just means summing up the "measure" for all actions in the state, that is reached by taking this action.

**Comment by sheim** [comment]
We chatted about this before leaving, the problem is that if you integrate over the actions, you are "looking into the future", and the actual measure after the first step depends on your policy. This gets tricky since the policy is "active sampling" and will change with each updated sample. It's the same problem as doing off-policy learning for more than just one step (like if you want to do temporal difference). Instead, if we take a static measure over Q, such as "number of qs with measure higher than $\lambda$", then this is just considering the safety for one step ahead, and this works.

**Comment by sheim** [comment]
Therefore, the measure needs to be applied in a "flat" manner to the set. For example the volume, i.e. simply counting the number of actions that are above the threshold, or something a bit more sophisticated taking the shape into consideration (e.g. you could take the volume of the largest convex subset, or take the moment-of-inertia of the shape, etc.)

**Comment by alexBeuth** [comment]
Sorry, I am still confused. Isn't the volume the (double, triple ..) integral? I still do not see how the integral is not "flat" and how it is different than, say, the mean with regard to to "looking into the future".

**Comment by sheim** [comment]
We're looking at the volume (integral assuming uniform density of the body), not the mass (integral that actually uses the probability density).
